import type { SlotGameConfig } from './slots.types.js';

export const SLOT_GAMES_CONFIG: Record<string, SlotGameConfig> = {
  'royal-gold-777': {
    id: 'royal-gold-777',
    name: 'Royal Gold 777',
    subtitle: 'Classic 3-Reel Vegas Slot',
    emoji: '👑',
    reels: 3,
    symbols: ['7️⃣', '👑', '💎', '🔔', '🍒', '🍋'],
    paytable: {
      jackpot777: 100,
      threeOfAKind: 15,
      twoOfAKind: 2,
    },
    minBet: 10,
    maxBet: 1000,
    targetRtp: 95,
    enabled: true,
    wildSymbol: '👑',
    jackpotMultiplier: 100,
  },
  'dragon-fortune-5x': {
    id: 'dragon-fortune-5x',
    name: 'Dragon Fortune',
    subtitle: '5-Reel Mythic Video Slot',
    emoji: '🐉',
    reels: 5,
    symbols: ['🐉', '👑', '💎', '🔥', '🔮', '🧧', '🪙'],
    paytable: {
      jackpot777: 250,
      threeOfAKind: 25,
      fourOfAKind: 75,
      fiveOfAKind: 250,
      twoOfAKind: 3,
    },
    minBet: 50,
    maxBet: 2500,
    targetRtp: 94,
    enabled: true,
    wildSymbol: '🐉',
    scatterSymbol: '🧧',
    jackpotMultiplier: 250,
  },
  'mega-fruit-party': {
    id: 'mega-fruit-party',
    name: 'Mega Fruit Party',
    subtitle: '3-Reel Arcade Juicy Spins',
    emoji: '🍓',
    reels: 3,
    symbols: ['⭐', '🍓', '🍉', '🍇', '🍌', '🍒'],
    paytable: {
      jackpot777: 75,
      threeOfAKind: 12,
      twoOfAKind: 1.8,
    },
    minBet: 10,
    maxBet: 500,
    targetRtp: 96,
    enabled: true,
    wildSymbol: '⭐',
    jackpotMultiplier: 75,
  },
  'diamond-deluxe': {
    id: 'diamond-deluxe',
    name: 'Diamond Deluxe',
    subtitle: '3-Reel Gem Deluxe Classic',
    emoji: '💎',
    reels: 3,
    symbols: ['💎', '👑', '🔮', '✨', '💙', '💍'],
    paytable: {
      jackpot777: 150,
      threeOfAKind: 20,
      twoOfAKind: 2.5,
    },
    minBet: 20,
    maxBet: 1500,
    targetRtp: 95,
    enabled: true,
    wildSymbol: '💎',
    jackpotMultiplier: 150,
  },
  'wild-safari': {
    id: 'wild-safari',
    name: 'Wild Safari',
    subtitle: '5-Reel Mythic Safari Video Slot',
    emoji: '🦁',
    reels: 5,
    symbols: ['🦁', '🐘', '🦏', '🦒', '🦓', '🃏'],
    paytable: {
      jackpot777: 300,
      threeOfAKind: 30,
      fourOfAKind: 100,
      fiveOfAKind: 300,
      twoOfAKind: 3.5,
    },
    minBet: 50,
    maxBet: 3000,
    targetRtp: 94,
    enabled: true,
    wildSymbol: '🦁',
    jackpotMultiplier: 300,
  },
  'golden-pharaoh': {
    id: 'golden-pharaoh',
    name: 'Golden Pharaoh',
    subtitle: '5-Reel Flagship Egyptian Slot',
    emoji: '𓀾',
    reels: 5,
    symbols: ['𓀾', '👁️', '𓆣', '🪙', '🏺', '📜', '✨'],
    paytable: {
      jackpot777: 500,
      threeOfAKind: 50,
      fourOfAKind: 150,
      fiveOfAKind: 500,
      twoOfAKind: 5,
    },
    minBet: 100,
    maxBet: 5000,
    targetRtp: 93,
    enabled: true,
    wildSymbol: '𓀾',
    scatterSymbol: '👁️',
    jackpotMultiplier: 500,
  },
};
